### ISSUE TITLE
Add NODE_ENV as value for api to allow graphql playground

### ISSUE THREAD

**Issue by cmbirk** [slingshotlabs/reaction-oss-helm-chart#12]
It looks like we need to enable a setting for NODE_ENV other than production so that it's possible to create a deployment that has a graphql playground available.

**Comment by balibebas** [comment]
Thinking out loud. It sounds like OP is looking to enable GQL playground for `development` builds (substitute for your own environments). Is that correct? I noticed in the Reaction Development platform itself graphql is available for `production` builds at the URL `https://api.reaction.local/graphql` (substitute for your URL) thereby making the API available to outside consumers. Is that something which servicing this issue could help achieve?

**Comment by dcrdev** [comment]
So because NODE_ENV = production , the default is that playground is disabled. Playground can be independently controlled via the GRAPHQL_PLAYGROUND_ENABLED var, I would be happy to add that as a chart value. NODE_ENV as a chart value is not typically the done thing, so not sure on that one.

I am however contemplating adding an additional environment variables section to the values, that would allow you to inject your own custom environment variables without modifying the chart.

Thoughts?

**Comment by balibebas** [comment]
> I am however contemplating adding an additional environment variables section to the values, that would allow you to inject your own custom environment variables without modifying the chart.

I haven't personally tried the Helm Chart yet but it's on my list of TODOs. If it works anything like Compose files, perhaps an `override.yml` file of some sort could be used to adjust existing ENV vars only so as not to confuse what's in Reaction proper with the Helm Chart. Otherwise a prefix (e.g. `NAMESPACE_FOO` could be used).

**Comment by dcrdev** [comment]
Added support for playground in https://github.com/slingshotlabs/reaction-oss-helm-chart/pull/14

Closing this issue and will create another for adhoc config.
