### ISSUE TITLE
Websocket errors causing admin to load extremely slowly

### ISSUE THREAD

**Issue by cmbirk** [slingshotlabs/reaction-oss-helm-chart#24]
I'm getting a ton of these errors on the admin side which is causing a very slow load:

```
Firefox can’t establish a connection to the server at wss://example.com/sockjs/183/b1ktd5sf/websocket. e91c6e6cd55e480b2e7fe25514ac0bc01a831f74.js:612:22976
The connection to wss://example.com/sockjs/183/b1ktd5sf/websocket was interrupted while the page was loading.
```

Are websockets enabled with this helm chart or would this be caused by a different issue?

**Comment by dcrdev** [comment]
@cmbirk what are the values of:

proxy-read-timeout and proxy-send-timeout ?

^ Assuming you're using nginx...

**Comment by cmbirk** [comment]
They're both 3600 in the admin panel configuration

**Comment by dcrdev** [comment]
I didn't read your error message properly - that is entirely caused by the admin ui itself and not this chart or nginx. The problem is that the ws client is not waiting for a "connection_ack" message, which on first connection is slow because it has to authenticate and it's not in the queue.

However I don't think this is actually a problem as it's reconnecting within milliseconds and proceeding to get a successful ack, even more than that it's actually receiving/sending successful heartbeats.

As you can see here where the socket connections with a 'finished' state lead in extremely quickly to new connections with a 101 status - this is correct.
![image](https://user-images.githubusercontent.com/8715048/98624204-366f3b00-2305-11eb-88bc-2109519b98a3.png)

The /websocket endpoint is successfully receiving and sending messages:
![image](https://user-images.githubusercontent.com/8715048/98624420-b2698300-2305-11eb-8d54-31f545dad728.png)

The /graphql subscription endpoint is getting that ack back:
![image](https://user-images.githubusercontent.com/8715048/98624483-d2994200-2305-11eb-9a3f-146cb723ea17.png)

And graphql subscriptions appear to work OK - albeit I'm not sure specifically where the admin interface uses/needs them:
![image](https://user-images.githubusercontent.com/8715048/98624673-3459ac00-2306-11eb-931c-8197a89d1010.png)

So yeah I'm not sure that your slowness is related to websockets... could you try using the profiler in dev tools to see if we can pinpoint the problem?

**Comment by dcrdev** [comment]
Also the ws client on the storefront has the correct flow of connecting and then waiting a reasonable amount of time for a connection_ack:
![image](https://user-images.githubusercontent.com/8715048/98626037-b519a780-2308-11eb-89cd-92fc28661650.png)

**Comment by cmbirk** [comment]
The WS errors are throwing either `400` or `404` errors. I don't _think_ it's an ack issue. Are you not getting any of those issues with a default install?

**Comment by dcrdev** [comment]
No not a single 404 or 400:

![image](https://user-images.githubusercontent.com/8715048/99523321-d1fc4d80-298e-11eb-98fb-42f0689359a6.png)

**Comment by cmbirk** [comment]
Hmm. Ok, it's definitely something in my infrastructure then. I'll look into whether this may be a port issue in AWS.

**Comment by cmbirk** [comment]
Looks like these may be of use: 
https://github.com/kubernetes/ingress-nginx/issues/1822

and gist from the bottom of that issue: https://gist.github.com/jsdevtom/7045c03c021ce46b08cb3f41db0d76da#file-ingress-service-yaml

Will update the ticket with what I find

**Comment by cmbirk** [comment]
Interestingly I've re-deployed with your changes to this repo and it seems to be working now! Going to close this ticket, and thank you for the feedback here.
