### ISSUE TITLE
Include ability to provide postgresql connection string

### ISSUE THREAD

**Issue by cmbirk** [slingshotlabs/reaction-oss-helm-chart#7]
Right now we have the ability to provide a MongoDB connection string outside of the K8S cluster. We should include the same for Postgres, as a production setup really shouldn't include that db in containers

**Comment by dcrdev** [comment]
Yup I agree - this was initially built with the intention of pulling hydra as a subchart; but their chart at the time was not ideally set up for running a sidecart to set up alongside a ha deployment, so I just implemented it myself. The official hydra chart deprecated the community maintained chart in the mainline repos, I think it's moved on since I did this.

Using the official chart as a subchart - would expose their config options and hence solve this problem. Or a simple conditional statement around what we already have would work as well.

I'll get to this along with updating to the latest rc images soon - if this is needed now, would be awesome if you could submit a pr.

**Comment by cmbirk** [comment]
I'll take a first pass at this and get a PR opened

**Comment by dcrdev** [comment]
Addressed in 221ad9fa3f5b01b93393957e37e4e1a166434e9d
